version: '3.7'

networks:
  nginx_proxy:
    external: true

services:

  nginx: # https://hub.docker.com/_/nginx
    image: nginx:1.18.0
    container_name: nginx
    restart: unless-stopped
    networks:
      - nginx_proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      #- ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot: # https://hub.docker.com/r/certbot/certbot
    image: certbot/certbot:v1.3.0
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
